// Curated list of sovereign states (countries) — the super-hubs the explorer's
// states toggle hides. Generated from Wikidata, NOT hand-maintained: every
// current UN member state (instance-of country `Q6256` + member-of UN `Q1065`)
// plus a few non-member states that recur in Israeli news (Palestine, Taiwan,
// Kosovo, the Holy See) and the historical Ottoman Empire. Each entry carries
// the Wikidata QID (the stable, primary match key) and every Hebrew name +
// alias, normalized to the same canonical form the pipeline stores entity names
// in (normalize.ts Layer 1), so the name fallback matches un-QID'd countries.
//
// Regenerate from the Wikidata Query Service (https://query.wikidata.org/sparql)
// with the query below, then normalize each label/alias the way the pipeline does
// (normalize.ts) and dedupe by QID. Add one-off non-country hubs in states.ts.
//
//   SELECT ?c ?label (GROUP_CONCAT(DISTINCT ?alt; separator="||") AS ?alts) WHERE {
//     ?c wdt:P31 wd:Q6256 . ?c wdt:P463 wd:Q1065 .          # country, member of the UN
//     ?c rdfs:label ?label . FILTER(LANG(?label)="he")
//     OPTIONAL { ?c skos:altLabel ?alt . FILTER(LANG(?alt)="he") }
//   } GROUP BY ?c ?label
//
// plus VALUES { wd:Q219060 wd:Q865 wd:Q1246 wd:Q237 wd:Q12560 } for the non-UN
// states (Palestine, Taiwan, Kosovo, Holy See) and the historical Ottoman Empire.

export interface CountryEntry {
  qid: string;
  names: string[];
}

export const COUNTRIES: readonly CountryEntry[] = [
  { qid: 'Q1036', names: ['אוגנדה'] },
  { qid: 'Q265', names: ['אוזבקיסטן', 'אוזבכיסתאן'] },
  { qid: 'Q40', names: ['אוסטריה'] },
  { qid: 'Q408', names: ['אוסטרליה'] },
  { qid: 'Q212', names: ['אוקראינה'] },
  { qid: 'Q77', names: ['אורוגוואי'] },
  { qid: 'Q227', names: ['אזרבייג׳ן', 'אזרבאיג׳אן', 'אזרביג׳אן', 'אזרביג׳ן', 'אזרבייג׳אן', 'הרפובליקה של אזרבייג׳ן'] },
  { qid: 'Q878', names: ['איחוד האמירויות הערביות', 'איחוד האמירויות', 'איחוד נסיכויות המפרץ', 'ברית האמירויות הערביות', 'האמירויות הערביות המאוחדות', 'מאע״מ', 'מאע״ם', 'מדינת האמירויות הערביות המאוחדות'] },
  { qid: 'Q38', names: ['איטליה'] },
  { qid: 'Q778', names: ['איי בהאמה'] },
  { qid: 'Q709', names: ['איי מרשל'] },
  { qid: 'Q685', names: ['איי שלמה'] },
  { qid: 'Q252', names: ['אינדונזיה'] },
  { qid: 'Q189', names: ['איסלנד'] },
  { qid: 'Q794', names: ['איראן', 'אירן'] },
  { qid: 'Q27', names: ['אירלנד', 'אייר', 'איירה', 'אירי', 'אירים', 'הרפובליקה האירית', 'דרום אירלנד', 'הרפובליקה של אירלנד'] },
  { qid: 'Q792', names: ['אל סלוודור'] },
  { qid: 'Q222', names: ['אלבניה'] },
  { qid: 'Q262', names: ['אלג׳יריה'] },
  { qid: 'Q916', names: ['אנגולה'] },
  { qid: 'Q228', names: ['אנדורה'] },
  { qid: 'Q781', names: ['אנטיגואה וברבודה'] },
  { qid: 'Q1050', names: ['אסוואטיני', 'סווזילנד'] },
  { qid: 'Q191', names: ['אסטוניה'] },
  { qid: 'Q889', names: ['אפגניסטן', 'אפגאניסטאן', 'אפגניסטאן'] },
  { qid: 'Q736', names: ['אקוודור', 'רפובליקת אקוודור'] },
  { qid: 'Q414', names: ['ארגנטינה'] },
  { qid: 'Q986', names: ['אריתריאה'] },
  { qid: 'Q399', names: ['ארמניה'] },
  { qid: 'Q30', names: ['ארצות הברית', 'אמריקה', 'ארה״ב', 'ארצות הברית של אמריקה', 'ארצות-הברית'] },
  { qid: 'Q115', names: ['אתיופיה', 'חבש'] },
  { qid: 'Q917', names: ['בהוטן', 'בוטאן', 'מדינת בוטאן'] },
  { qid: 'Q963', names: ['בוטסואנה'] },
  { qid: 'Q219', names: ['בולגריה', 'בולגרי'] },
  { qid: 'Q750', names: ['בוליביה'] },
  { qid: 'Q225', names: ['בוסניה והרצגובינה'] },
  { qid: 'Q967', names: ['בורונדי'] },
  { qid: 'Q965', names: ['בורקינה פאסו'] },
  { qid: 'Q398', names: ['בחריין', 'בחרין', 'ממלכת בחריין'] },
  { qid: 'Q184', names: ['בלארוס', 'בלרוס', 'רוסיה הלבנה'] },
  { qid: 'Q31', names: ['בלגיה'] },
  { qid: 'Q242', names: ['בליז'] },
  { qid: 'Q902', names: ['בנגלדש'] },
  { qid: 'Q962', names: ['בנין'] },
  { qid: 'Q244', names: ['ברבדוס', 'המשפט בברבדוס'] },
  { qid: 'Q921', names: ['ברוניי', 'סולטנות ברוניי', 'ברוניי דארוסלאם'] },
  { qid: 'Q155', names: ['ברזיל'] },
  { qid: 'Q977', names: ['ג׳יבוטי'] },
  { qid: 'Q766', names: ['ג׳מייקה'] },
  { qid: 'Q230', names: ['גאורגיה', 'גרוזיה', 'גורג׳יה', 'גורג׳יסטן', 'גיאורגיה', 'סַכָּרְתְבֵלוֹ', 'סכרתוולו', 'סקרטבלו', 'סקרטוולו'] },
  { qid: 'Q117', names: ['גאנה'] },
  { qid: 'Q1000', names: ['גבון'] },
  { qid: 'Q774', names: ['גואטמלה', 'גואטמאלה', 'גוואטמלה', 'גווטמלה', 'גוטמלה', 'רפובליקת גואטמלה'] },
  { qid: 'Q734', names: ['גיאנה'] },
  { qid: 'Q1006', names: ['גינאה'] },
  { qid: 'Q1007', names: ['גינאה ביסאו'] },
  { qid: 'Q983', names: ['גינאה המשוונית'] },
  { qid: 'Q1005', names: ['גמביה'] },
  { qid: 'Q183', names: ['גרמניה', 'הרפובליקה הפדרלית של גרמניה'] },
  { qid: 'Q769', names: ['גרנדה'] },
  { qid: 'Q784', names: ['דומיניקה'] },
  { qid: 'Q258', names: ['דרום אפריקה'] },
  { qid: 'Q958', names: ['דרום סודאן'] },
  { qid: 'Q790', names: ['האיטי'] },
  { qid: 'Q826', names: ['האיים המלדיביים', 'המלדיביים'] },
  { qid: 'Q12560', names: ['האימפריה העות׳מאנית', 'האימפריה הטורקית'] },
  { qid: 'Q668', names: ['הודו'] },
  { qid: 'Q28', names: ['הונגריה'] },
  { qid: 'Q783', names: ['הונדורס'] },
  { qid: 'Q702', names: ['המדינות הפדרטיביות של מיקרונזיה', 'מיקרונזיה'] },
  { qid: 'Q145', names: ['הממלכה המאוחדת', 'בריטניה', 'הממלכה המאוחדת של בריטניה הגדולה וצפון אירלנד'] },
  { qid: 'Q928', names: ['הפיליפינים'] },
  { qid: 'Q786', names: ['הרפובליקה הדומיניקנית'] },
  { qid: 'Q974', names: ['הרפובליקה הדמוקרטית של קונגו', 'זאיר'] },
  { qid: 'Q929', names: ['הרפובליקה המרכז-אפריקאית', 'רמ״א', 'אובאנגי שארי', 'אובנגי שרי', 'הרפובליקה המרכז-אפריקנית', 'הרפובליקה של מרכז אפריקה', 'ר.מ.א', 'רפובליקת מרכז אפריקה'] },
  { qid: 'Q148', names: ['הרפובליקה העממית של סין', 'סין'] },
  { qid: 'Q971', names: ['הרפובליקה של קונגו'] },
  { qid: 'Q881', names: ['וייטנאם'] },
  { qid: 'Q686', names: ['ונואטו'] },
  { qid: 'Q717', names: ['ונצואלה'] },
  { qid: 'Q954', names: ['זימבבואה'] },
  { qid: 'Q953', names: ['זמביה'] },
  { qid: 'Q1008', names: ['חוף השנהב'] },
  { qid: 'Q865', names: ['טאיוואן', 'הרפובליקה הסינית'] },
  { qid: 'Q863', names: ['טג׳יקיסטן', 'טאג׳יקיסטן', 'טג׳יקיסטאן', 'תאג׳יכיסתאן'] },
  { qid: 'Q672', names: ['טובאלו'] },
  { qid: 'Q945', names: ['טוגו'] },
  { qid: 'Q678', names: ['טונגה'] },
  { qid: 'Q43', names: ['טורקיה', 'תורכיה', 'הרפובליקה הטורקית', 'הרפובליקה התורכית', 'טורכיה', 'טורקייה', 'תורקיה'] },
  { qid: 'Q874', names: ['טורקמניסטן', 'טורקמניה', 'טורקמניסטאן', 'תורכמניסטן'] },
  { qid: 'Q924', names: ['טנזניה'] },
  { qid: 'Q754', names: ['טרינידד וטובגו'] },
  { qid: 'Q41', names: ['יוון', 'הרפובליקה היוונית'] },
  { qid: 'Q17', names: ['יפן', 'יפאן'] },
  { qid: 'Q810', names: ['ירדן', 'הממלכה הירדנית ההאשמית'] },
  { qid: 'Q801', names: ['ישראל', 'מדינת ישראל'] },
  { qid: 'Q817', names: ['כווית'] },
  { qid: 'Q1011', names: ['כף ורדה'] },
  { qid: 'Q819', names: ['לאוס'] },
  { qid: 'Q822', names: ['לבנון'] },
  { qid: 'Q1016', names: ['לוב'] },
  { qid: 'Q32', names: ['לוקסמבורג', 'הדוכסות הגדולה של לוקסמבורג', 'לוכסמבורג', 'לוקסנבורג'] },
  { qid: 'Q211', names: ['לטביה'] },
  { qid: 'Q1014', names: ['ליבריה'] },
  { qid: 'Q37', names: ['ליטא'] },
  { qid: 'Q347', names: ['ליכטנשטיין'] },
  { qid: 'Q1013', names: ['לסוטו'] },
  { qid: 'Q1025', names: ['מאוריטניה'] },
  { qid: 'Q1027', names: ['מאוריציוס'] },
  { qid: 'Q912', names: ['מאלי'] },
  { qid: 'Q1019', names: ['מדגסקר'] },
  { qid: 'Q219060', names: ['מדינה פלסטינית', 'פלסטין', 'הרשות הפלסטינית', 'מדינת פלסטין'] },
  { qid: 'Q1029', names: ['מוזמביק'] },
  { qid: 'Q217', names: ['מולדובה'] },
  { qid: 'Q711', names: ['מונגוליה'] },
  { qid: 'Q236', names: ['מונטנגרו', 'ההר השחור'] },
  { qid: 'Q235', names: ['מונקו'] },
  { qid: 'Q574', names: ['מזרח טימור'] },
  { qid: 'Q836', names: ['מיאנמר'] },
  { qid: 'Q1020', names: ['מלאווי'] },
  { qid: 'Q833', names: ['מלזיה'] },
  { qid: 'Q233', names: ['מלטה'] },
  { qid: 'Q29999', names: ['ממלכת ארצות השפלה', 'ממלכת הולנד'] },
  { qid: 'Q756617', names: ['ממלכת דנמרק'] },
  { qid: 'Q79', names: ['מצרים'] },
  { qid: 'Q221', names: ['מקדוניה הצפונית', 'הרפובליקה היוגוסלבית לשעבר של מקדוניה', 'רפובליקת מקדוניה'] },
  { qid: 'Q96', names: ['מקסיקו', 'מכסיקו'] },
  { qid: 'Q1028', names: ['מרוקו'] },
  { qid: 'Q697', names: ['נאורו'] },
  { qid: 'Q20', names: ['נורווגיה', 'נורבגיה', 'ממלכת נורבגיה', 'ממלכת נורווגיה'] },
  { qid: 'Q1033', names: ['ניגריה', 'הרפובליקה הפדרלית של ניגריה'] },
  { qid: 'Q664', names: ['ניו זילנד'] },
  { qid: 'Q1032', names: ['ניז׳ר'] },
  { qid: 'Q811', names: ['ניקרגואה'] },
  { qid: 'Q1030', names: ['נמיביה'] },
  { qid: 'Q837', names: ['נפאל'] },
  { qid: 'Q1039', names: ['סאו טומה ופרינסיפה'] },
  { qid: 'Q1049', names: ['סודאן'] },
  { qid: 'Q1045', names: ['סומליה'] },
  { qid: 'Q858', names: ['סוריה'] },
  { qid: 'Q730', names: ['סורינאם', 'גיאנה ההולנדית'] },
  { qid: 'Q1044', names: ['סיירה לאון'] },
  { qid: 'Q1042', names: ['סיישל'] },
  { qid: 'Q334', names: ['סינגפור'] },
  { qid: 'Q215', names: ['סלובניה'] },
  { qid: 'Q214', names: ['סלובקיה'] },
  { qid: 'Q683', names: ['סמואה'] },
  { qid: 'Q238', names: ['סן מרינו'] },
  { qid: 'Q1041', names: ['סנגל'] },
  { qid: 'Q757', names: ['סנט וינסנט והגרנדינים'] },
  { qid: 'Q760', names: ['סנט לוסיה'] },
  { qid: 'Q763', names: ['סנט קיטס ונוויס'] },
  { qid: 'Q29', names: ['ספרד'] },
  { qid: 'Q403', names: ['סרביה'] },
  { qid: 'Q854', names: ['סרי לנקה'] },
  { qid: 'Q842', names: ['עומאן', 'סולטנות עומאן', 'עומן'] },
  { qid: 'Q796', names: ['עיראק', 'עירק'] },
  { qid: 'Q851', names: ['ערב הסעודית', 'סעודיה'] },
  { qid: 'Q36', names: ['פולין', 'פולניה'] },
  { qid: 'Q45', names: ['פורטוגל'] },
  { qid: 'Q712', names: ['פיג׳י'] },
  { qid: 'Q33', names: ['פינלנד'] },
  { qid: 'Q695', names: ['פלאו'] },
  { qid: 'Q804', names: ['פנמה'] },
  { qid: 'Q691', names: ['פפואה גינאה החדשה', 'פפואה ניו גיני'] },
  { qid: 'Q843', names: ['פקיסטן'] },
  { qid: 'Q733', names: ['פרגוואי', 'פארגוואי'] },
  { qid: 'Q419', names: ['פרו'] },
  { qid: 'Q657', names: ['צ׳אד'] },
  { qid: 'Q298', names: ['צ׳ילה'] },
  { qid: 'Q213', names: ['צ׳כיה', 'הרפובליקה הצ׳כית'] },
  { qid: 'Q142', names: ['צרפת'] },
  { qid: 'Q241', names: ['קובה'] },
  { qid: 'Q739', names: ['קולומביה'] },
  { qid: 'Q970', names: ['קומורו'] },
  { qid: 'Q1246', names: ['קוסובו', 'הרפובליקה של קוסובו'] },
  { qid: 'Q800', names: ['קוסטה ריקה'] },
  { qid: 'Q884', names: ['קוריאה הדרומית', 'דרום קוריאה', 'דרום-קוריאה', 'הרפובליקה של קוריאה', 'רפובליקת קוריאה'] },
  { qid: 'Q423', names: ['קוריאה הצפונית', 'צפון קוריאה'] },
  { qid: 'Q232', names: ['קזחסטן', 'קאזחסטאן', 'קזחסטאן', 'קזכסטן', 'רפובליקת קזחסטן'] },
  { qid: 'Q846', names: ['קטר', 'קטאר', 'קאטר', 'קאטאר'] },
  { qid: 'Q813', names: ['קירגיזסטן'] },
  { qid: 'Q710', names: ['קיריבטי'] },
  { qid: 'Q424', names: ['קמבודיה'] },
  { qid: 'Q1009', names: ['קמרון'] },
  { qid: 'Q16', names: ['קנדה'] },
  { qid: 'Q114', names: ['קניה'] },
  { qid: 'Q229', names: ['קפריסין'] },
  { qid: 'Q224', names: ['קרואטיה'] },
  { qid: 'Q237', names: ['קריית הוותיקן', 'ותיקן', 'הוותיקן', 'מדינת קריית הוותיקן', 'עיר הוותיקן'] },
  { qid: 'Q1037', names: ['רואנדה'] },
  { qid: 'Q218', names: ['רומניה'] },
  { qid: 'Q159', names: ['רוסיה', 'הפדרציה הרוסית'] },
  { qid: 'Q34', names: ['שוודיה', 'שבדיה'] },
  { qid: 'Q39', names: ['שווייץ', 'שוויץ'] },
  { qid: 'Q869', names: ['תאילנד', 'סיאם'] },
  { qid: 'Q948', names: ['תוניסיה', 'הרפובליקה התוניסאית', 'טוניסיה'] },
  { qid: 'Q805', names: ['תימן'] },
];
